# site settings
title: Jared Grimes
subtitle: Web developer 
email: jaredlgrimes@hotmail.com
description: I like to code
baseurl: # the subpath of your site, e.g. /blog
url: "http://jaredlgrimes.com" # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code:
country: 
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: http://www.facebook.com/calcislovecalcislife
github_url: http://www.github.com/comp0cker
gitlab_url: 
googleplus_url:
instagram_url: 
linkedin_url: https://www.linkedin.com/in/jaredlgrimes
pinterest_url:
slack_url:
twitter_url: https://twitter.com/comp0cker

# build settings
markdown: kramdown

sass:
  style: compressed
